# Generated by Django 5.2.16 on 2026-08-21 13:29

from django.db import migrations


def _generate_for_existing(apps, schema_editor):
    Property = apps.get_model("properties", "Property")
    props = list(Property.objects.all().order_by("id"))

    # Sequential starting value (no zero allowed)
    val = 1110
    for prop in props:
        val += 1
        while "0" in str(val):
            val += 1
        digits = f"{val:04d}" if val <= 9999 else f"{val:05d}"
        prop.internal_code = f"ZF_{digits}"
        prop.save(update_fields=["internal_code"])


def reverse_rewrite(apps, schema_editor):
    # Reverse is a no-op; original codes are lost intentionally per spec.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0010_alter_propertyimage_image"),
    ]

    operations = [
        migrations.RunPython(_generate_for_existing, reverse_rewrite),
    ]

