# Generated by Django 5.2.16 on 2026-08-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_adminprofile_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('password', 'رمز عبور'), ('sms', 'کد پیامکی')], default='password', max_length=20, verbose_name='روش ورود')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'روش ورود',
                'verbose_name_plural': 'روش ورود',
            },
        ),
        migrations.CreateModel(
            name='SmsLoginCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(db_index=True, max_length=16, verbose_name='شماره موبایل')),
                ('code_hash', models.CharField(max_length=255, verbose_name='کد (هش\u200cشده)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='انقضا')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='تلاش\u200cهای ناموفق')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ مصرف')),
            ],
            options={
                'verbose_name': 'کد ورود پیامکی',
                'verbose_name_plural': 'کدهای ورود پیامکی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmsProviderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smsir_api_key', models.CharField(blank=True, max_length=1024, verbose_name='کلید API اسمس\u200cدات\u200cآی\u200cآر')),
                ('smsir_line_number', models.CharField(blank=True, help_text='اختیاری؛ فقط اگر سرویس\u200cدهنده نیاز دارد وارد شود.', max_length=32, verbose_name='شماره خط اسمس\u200cدات\u200cآی\u200cآر')),
                ('smsir_template_id', models.CharField(blank=True, help_text='قالب تأیید (verify) در پنل اسمس\u200cدات\u200cآی\u200cآر.', max_length=64, verbose_name='شناسه قالب (templateId)')),
                ('kavenegar_api_key', models.CharField(blank=True, max_length=1024, verbose_name='کلید API کاوه\u200cنگار')),
                ('kavenegar_sender', models.CharField(blank=True, default='20006535', max_length=32, verbose_name='شماره فرستنده کاوه\u200cنگار')),
                ('kavenegar_template_name', models.CharField(blank=True, help_text='اختیاری؛ اگر تنظیم شود کد از طریق قالب (lookup) ارسال می\u200cشود، وگرنه پیام متنی ساده.', max_length=128, verbose_name='نام قالب احراز هویت کاوه\u200cنگار')),
                ('kavenegar_message', models.CharField(blank=True, default='کد ورود شما به زمینکس: {code}', help_text='متن سادهٔ پیامک؛ {code} با کد تأیید جایگزین می\u200cشود.', max_length=500, verbose_name='متن پیام (در صورت نبود قالب)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات پیامک',
                'verbose_name_plural': 'تنظیمات پیامک',
            },
        ),
    ]
